### ISSUE TITLE
AWS Nested Security Group doesn't work

### ISSUE THREAD

**Issue by rewiko** [jc1518/SSSG-Ninja#1]
Hi, 

I've tried the same thing, with an ELB/ALB and a global security group "SG Akamai" within 2 security group associated to this one, "SG Akamai" and "SG Akamai Staging".

The nested Security Group doesn't work, I can't reach my application. If I've associated the security group directly to the ELB, it works.

Any Idea ?
Thanks

**Comment by jc1518** [comment]
Hi @rewiko , you are correct. AWS does not support such nested security group. Nested security group only works the associated EC2 instances. I will update the doc to reflect that.
