### ISSUE TITLE
Take siteshield_map_ids, siteshield_sg_groups and trusted_cidr from environment?

### ISSUE THREAD

**Issue by schnoddelbotz** [jc1518/SSSG-Ninja#2]
Hi,

As the subjects states: Would it be possible to take those three variables from environment, too?
This would improve direct re-usability of SSSG-Ninja, I think...

Thanks for sharing SSSG-Ninja!

**Comment by jc1518** [comment]
@schnoddelbotz Technically, it is possible to take the three variables from environments. But personally, I prefer to use config files. The benefit is that it allows me to version control them as well.
